# Generated by Django 5.2.5 on 2025-08-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_comment_dislike_like_save'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='save',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
